// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://gmrxhgcuwtghjskikfug.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdtcnhoZ2N1d3RnaGpza2lrZnVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA1MDI5NzcsImV4cCI6MjA3NjA3ODk3N30.0BeQEs4hO_dlQq3dhDhdVPAR5jPLf7AR7wqn6FMFFD0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);